[tool.poetry]
name = "confidential"
version = "0.1.0"
description = ""
authors = ["Daniel van Flymen <dvf@candidco.com>"]

[tool.poetry.dependencies]
python = "^3.5"
boto3 = "^1.9"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.plugins."console_scripts"]
"confidential" = "confidential.secrets_manager:decrypt_secret"
