name: pytest

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry>=0.12
        poetry config virtualenvs.create false --local
        poetry install
    - name: Test with pytest
      run: |
        pytest

  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push to s3
        env:
          AWS_S3_BUCKET: pypi.candidco.com
          SOURCE_DIR: "."
        run: |
          pip install s3pypi==0.11.0
          pip install poetry2setup
          poetry2setup > setup.py
          s3pypi --bucket pypi.candidco.com --private || echo "ERROR: push failed for $package";